export const genres = [
  'Action',
  'Adventure',
  'Avant Garde',
  'Boys Love',
  'Comedy',
  'Demons',
  'Drama',
  'Ecchi',
  'Fantasy',
  'Girls Love',
  'Gourmet',
  'Harem',
  'Horror',
  'Isekai',
  'Iyashikei',
  'Josei',
  'Kids',
  'Magic',
  'Mahou Shoujo',
  'Martial Arts',
  'Mecha',
  'Military',
  'Music',
  'Mystery',
  'Parody',
  'Psychological',
  'Reverse Harem',
  'Romance',
  'School',
  'Sci-Fi',
  'Seinen',
  'Shoujo',
  'Shounen',
  'Slice of Life',
  'Space',
  'Sports',
  'Super Power',
  'Supernatural',
  'Suspense',
  'Thriller',
  'Vampire',
];
export const types = ['manga', 'one-Shot', 'doujinshi', 'novel', 'manhwa', 'manhua'];

export const validQueries = ['type', 'genre', 'newest', 'updated', 'added'];
